// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJv1ZDB8W9HJNjAM9Gpk3pH1hdfw0JYXI',
    appId: '1:879939169058:web:4ea9bd812cb97e9b75137b',
    messagingSenderId: '879939169058',
    projectId: 'evidence-knih-d5dd1',
    authDomain: 'evidence-knih-d5dd1.firebaseapp.com',
    storageBucket: 'evidence-knih-d5dd1.firebasestorage.app',
    measurementId: 'G-BY1K8BHXZN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHL_0iM5ALTL6qzpKkcPdwJI6KxWuJrbM',
    appId: '1:879939169058:android:9531d176f756ef2d75137b',
    messagingSenderId: '879939169058',
    projectId: 'evidence-knih-d5dd1',
    storageBucket: 'evidence-knih-d5dd1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNo2RO5nOWUJwd-Hs39a-fyaFasWZUZkA',
    appId: '1:879939169058:ios:dbf9394bb02660a875137b',
    messagingSenderId: '879939169058',
    projectId: 'evidence-knih-d5dd1',
    storageBucket: 'evidence-knih-d5dd1.firebasestorage.app',
    iosBundleId: 'com.example.evidenceKnih',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNo2RO5nOWUJwd-Hs39a-fyaFasWZUZkA',
    appId: '1:879939169058:ios:dbf9394bb02660a875137b',
    messagingSenderId: '879939169058',
    projectId: 'evidence-knih-d5dd1',
    storageBucket: 'evidence-knih-d5dd1.firebasestorage.app',
    iosBundleId: 'com.example.evidenceKnih',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJv1ZDB8W9HJNjAM9Gpk3pH1hdfw0JYXI',
    appId: '1:879939169058:web:64e4272451b03db775137b',
    messagingSenderId: '879939169058',
    projectId: 'evidence-knih-d5dd1',
    authDomain: 'evidence-knih-d5dd1.firebaseapp.com',
    storageBucket: 'evidence-knih-d5dd1.firebasestorage.app',
    measurementId: 'G-PDT4Z00J6L',
  );
}
